---
- name: Create Security Group with All Traffic Allowed
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create public route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_info.vpc.id }}"
        tags:
          Name: my-public-route-table
        state: present
      register: public_rt_info

    - name: Add route to Internet Gateway
      amazon.aws.ec2_vpc_route:
        route_table_id: "{{ public_rt_info.route_table.id }}"
        dest: 0.0.0.0/0
        gateway_id: "{{ igw_info.gateway_id }}"
        state: present

    - name: Associate public subnet with public route table
      amazon.aws.ec2_vpc_route_table_association:
        subnet_id: "{{ public_subnet_info.subnet.id }}"
        route_table_id: "{{ public_rt_info.route_table.id }}"
        state: present
