- name: Load environment-specific variables
  ansible.builtin.include_vars:
    file: "../keypair/vars/main.yml"
  
- name: Create EC2 Key Pair if it doesn't exist
  amazon.aws.ec2_key:
    name: "{{ key_pair_name }}"
    region: "us-east-1"
    state: present
#    wait: true
  register: ec2_key_result

- name: Save private key to local file
  ansible.builtin.copy:
    content: "{{ ec2_key_result.key.private_key }}"
    dest: "{{ key_pair_path }}"
    mode: '0400'
  when: ec2_key_result.changed
# set_fact:
#   key_name: "{{key_pair_name}}" 

#- name: Display message about key pair creation
#  ansible.builtin.debug:
#    msg: "EC2 Key Pair '{{ key_pair_name }}' created and private key saved to '{{ key_pair_path }}'."
#  when: ec2_key_result.changed
#  set_fact:
#    key_name: "{{key_pair_name}}"
