- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3-pip

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

#- name: Add Docker’s official GPG key (saved in /etc/apt/keyrings)
#  ansible.builtin.get_url:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    dest: /etc/apt/keyrings/docker.gpg
#    mode: '0644'
#  register: docker_gpg_key

- name: Add GPG
  ansible.builtin.command: |
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

- name: Add Docker Repo
  ansible.builtin.command: |
   echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null 
  #become: yes
  #become_user: myappuser


#- name: Add Docker repository for current Ubuntu release
#  ansible.builtin.apt_repository:
#    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
#    filename: docker
#    state: present
#  become: yes
#  become_user: myappuser

#- name: Add Docker GPG apt key
#  ansible.builtin.apt_key:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    state: present
#

#- name: Add Docker GPG key
#  ansible.builtin.shell: |
#    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
#  args:
#    creates: /etc/apt/keyrings/docker.gpg
#  become: yes

#- name: Add Docker repository
#  ansible.builtin.apt_repository:
#    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
#    state: present
#    update_cache: yes

#- name: Add Docker apt repository
#  ansible.builtin.apt_repository:
#    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
#    state: present
#    filename: docker
#  become: yes

- name: Install Docker Engine
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-docker
    - docker-compose-plugin

#- name: Install Docker Compose 
#  ansible.builtin.pip:
#    name: docker-compose
#    state: present
